// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ1EapTFP-TKLD98KEgXLDM5KG33zrfAs',
    appId: '1:496204255608:web:d3662e28c95ae99046788d',
    messagingSenderId: '496204255608',
    projectId: 'naya-menu-478de',
    authDomain: 'naya-menu-478de.firebaseapp.com',
    storageBucket: 'naya-menu-478de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWqvB6OxI2MD6zAXEATj6pOs4AkxPJFwQ',
    appId: '1:496204255608:android:72b7de6ac880c4c146788d',
    messagingSenderId: '496204255608',
    projectId: 'naya-menu-478de',
    storageBucket: 'naya-menu-478de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr97e8afSvAbeP5UGYAODvefrDzf_fs7c',
    appId: '1:496204255608:ios:d68afed6f1b7793646788d',
    messagingSenderId: '496204255608',
    projectId: 'naya-menu-478de',
    storageBucket: 'naya-menu-478de.appspot.com',
    iosBundleId: 'com.example.nayaMenu',
  );

}